# Generated by Django 4.2.16 on 2026-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('annotation_type', models.CharField(choices=[('algorithm_update', 'Google Algorithm Update'), ('seo_campaign', 'SEO Campaign Launch'), ('website_migration', 'Website Migration'), ('content_release', 'Content Release'), ('product_launch', 'Product Launch'), ('other', 'Other')], default='other', max_length=30)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
