# Generated by Django 4.2.16 on 2026-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=500)),
                ('monthly_searches', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('transactional', 'Transactional'), ('commercial', 'Commercial')], db_index=True, default='informational', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], db_index=True, default='active', max_length=10)),
                ('rank', models.FloatField(blank=True, db_index=True, null=True)),
                ('previous_rank', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], db_index=True, default='desktop', max_length=10)),
                ('source_type', models.CharField(choices=[('organic', 'Organic'), ('paid', 'Paid'), ('direct', 'Direct'), ('referral', 'Referral')], db_index=True, default='organic', max_length=10)),
                ('clicks', models.IntegerField(db_index=True, default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('landing_page', models.URLField(blank=True, max_length=2000)),
                ('is_priority', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-clicks'],
                'indexes': [models.Index(fields=['category', 'status'], name='keywords_ke_categor_b1bb3f_idx'), models.Index(fields=['device_type', 'source_type'], name='keywords_ke_device__6f5abe_idx'), models.Index(fields=['rank', 'clicks'], name='keywords_ke_rank_9ea94f_idx')],
            },
        ),
    ]
